# ================================================
# Chainsaw
# ================================================
#
# Install cargo make to run these tasks:
#   cargo install cargo-make

[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.tests]
command = "cargo"
args = [ "llvm-cov", "nextest" ]
dependencies = [ "install-llvm-cov", "install-nextest" ]

[tasks.docs]
command = "cargo"
args = ["doc"]

[tasks.grpc]
install_crate = "grpc-build"
command = "grpc_build"
args = [
     "build",
     "--in-dir",
     "chainsaw-proto/proto/helloworld.proto",
     "--out-dir",
     "chainsaw-proto/src/grpc",
     "-f", # force output
     "-s", # generate server impl
     "-c", # generate client impl
]

# Installation targets must be used to define multiple dependency crates for a
# single target.
#
# See: https://github.com/sagiegurari/cargo-make#multiple-installations
[tasks.install-nextest]
install_crate = { crate_name = "cargo-nextest" }

[tasks.install-llvm-cov]
install_crate = { rustup_component_name = "llvm-tools-preview" }
