{{- $fullName := include "chainsaw-http.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: {{ $svcPort }}
      name: http
      protocol: HTTP
    hosts:
    - "*"
