{{- $fullName := include "chainsaw-http.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ $fullName }}
  http:
  - match:
    - uri:
        exact: /metrics
    - uri:
        prefix: /chainsaw/
    - uri:
        prefix: /xiv/
    route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ $svcPort }}
