[package]
name = "chainsaw-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
# grpc and protobuf implementations
tonic = "0.6"
tonic-health = "0.5"
chainsaw-proto = { version = "0.1", path = "../chainsaw-proto" }

# http application framework
axum = "0.4.5"
tower = "0.4.11"
tower-http = { version = "0.2.2", features = ["trace"] }
hyper = "0.14.17"

# async runtime
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "tracing", "signal", "parking_lot"] }

# structured logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter", "json"] }
console-subscriber = { version = "0.1.2", features = ["parking_lot"] }
tracing-error = "0.2"
tracing-log = "0.1"
color-eyre = "0.6"

# metrics
prometheus = { version = "0.13", features = ["process"] }

# configuration
config = "0.11"
serde = { version = "1.0", features = ["derive"] }
